site_name: Reliability Hub
site_url: https://marcocatalan.github.io/reliability-hub/
site_author: Marco Catalán
site_description: Centralized SRE & Data Engineering Standards

theme:
  name: material
  features:
    - navigation.tabs        # Pestañas estilo Google
    - navigation.sections
    - toc.integrate
  palette: 
    - scheme: default
      primary: teal          # Color profesional
      accent: purple

plugins:
  - search
  - blog:                    # ¡Activa el modo Blog!
      blog_dir: blog
      post_url_date_format: yyyy/MM/dd

nav:
  - Home: index.md
  - Blog: blog/
  - Modules:
      - 'Infrastructure as Code': modules/iac.md
      - 'Observability Stack': modules/observability.md
  - 'About Me': about.md
